### ISSUE TITLE
print.experiment error

### ISSUE THREAD

**Issue by meta00** [r-and-gama/rama#20] opened 2018-12-10 18:24 UTC
Check this gaml, name of parameters contains space etc. by running

```r
out <- load_experiment("main", "Regression.gaml")
out
```
[Regression.gaml.zip](https://github.com/r-and-gama/rama/files/2664470/Regression.gaml.zip)

**Comment by choisy** [comment] 2018-12-10 18:31
Can somebody provides the location of the GAML file in the GAMA file hierarchy please?

**Comment by choisy** [comment] 2018-12-10 18:43
The example GAML file does not correspond to the example. Please send the good GAML file.

**Comment by choisy** [comment] 2018-12-10 18:46
Regression.gaml seems to be a link, not a file.

**Comment by meta00** [comment] 2018-12-10 18:51
good one uploaded

**Comment by LucieContamin** [comment] 2018-12-12 07:54
Fixed in pull-request #15

**Closed by LucieContamin** 2018-12-12 07:54 UTC
